spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    com.ll.exam.app__2023_10_31.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  jwt:
    secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey